POST http://localhost:4545/api/v1/links/search/.png
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzI1NiJ9.Y21zaGFyZXJAZ21haWwuY29t.w2f2JOS8qyL8rzNE4UE6DvvuK2KVdofVizlryPt6xGs"
}

###